spring:
  datasource:
    url: jdbc:h2:mem:my_blanket
    driver-class-name: org.h2.Driver
    username: my_blanket_user
    password: password123456!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 30
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      password: mySecretPassword

# 실제 쿼리에 어떤 값이 들어갔는지 확인
#logging:
#  level:
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind:
#              TRACE